name: MapPictureExample
version: '${project.version}'
main: dev.potato.mappictureexample.MapPictureExample
api-version: '1.20'
commands:
  map:
    description: Gives the player a map with a custom image
    usage: /map
    aliases:
      - m